# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-32140-pc-klas6-7.esat.kuleuven.be/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::runtime_optimized 1
    set rt::partid xc7z010clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/ec67/hdl {
      /esat/micas-data/software/xilinx_vivado_2018.2/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /esat/micas-data/software/xilinx_vivado_2018.2/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /esat/micas-data/software/xilinx_vivado_2018.2/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/ec67/hdl {
      /users/students/r0713047/Eagle/Eagle7/src/bd/hdl/drone_wrapper.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_processing_system7_0_0/synth/drone_processing_system7_0_0.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/903d/hdl/TDP_bram.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/903d/hdl/keccakF400Permutation.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/903d/hdl/EAGLE_interface_CONTROL.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/903d/hdl/EAGLE_to_AXI_interface.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/903d/hdl/crypto2020_hash_ip_v1_v1_0_S00_AXI.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/903d/hdl/crypto2020_hash_ip_v1_v1_0.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_crypto2020_hash_ip_v1_0_0/synth/drone_crypto2020_hash_ip_v1_0_0.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_xadc_wiz_0_0/drone_xadc_wiz_0_0.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8942/hdl/SWIPT_2020_v1_0_S00_AXI.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8942/swipt_toplevel.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8942/hdl/Pwm.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8942/hdl/EnvelopeFollower.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8942/hdl/FrequencyTrackerII.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8942/hdl/SWIPT_2020_v1_0.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_SWIPT_2020_0_0/synth/drone_SWIPT_2020_0_0.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_xbar_0/synth/drone_xbar_0.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/synth/drone.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_8/synth/drone_auto_pc_8.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_7/synth/drone_auto_pc_7.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_6/synth/drone_auto_pc_6.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_5/synth/drone_auto_pc_5.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_4/synth/drone_auto_pc_4.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_3/synth/drone_auto_pc_3.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_2/synth/drone_auto_pc_2.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_1/synth/drone_auto_pc_1.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_0/synth/drone_auto_pc_0.v
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_auto_pc_9/synth/drone_auto_pc_9.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/5f23/src/PWM_measure.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/5f23/hdl/RC_v1_0_S00_AXI.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/5f23/hdl/RC_v1_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_RC_1_0/synth/drone_RC_1_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_RC_0_0/synth/drone_RC_0_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_axi_gpio_testpins_0/synth/drone_axi_gpio_testpins_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_axi_gpio_led_0/synth/drone_axi_gpio_led_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/7836/kill_switch.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_kill_switch_0_0/synth/drone_kill_switch_0_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/7486/hdl/PWM_AXI.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/7486/hdl/PWM_AXI_v1_0_S00_AXI.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/7486/hdl/PWM_AXI_v1_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_PWM_AXI_triple_0_0/synth/drone_PWM_AXI_triple_0_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_PWM_AXI_triple_3_0/synth/drone_PWM_AXI_triple_3_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_PWM_AXI_triple_5_0/synth/drone_PWM_AXI_triple_5_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_rst_processing_system7_0_100M_0/synth/drone_rst_processing_system7_0_100M_0.vhd
      /users/students/r0713047/Eagle/Eagle7/src/bd/ip/drone_PWM_AXI_triple_4_0/synth/drone_PWM_AXI_triple_4_0.vhd
    }
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_19 /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_12 /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_1 /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/67d8/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_2 /users/students/r0713047/Eagle/Eagle7/src/bd/ipshared/7aff/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib xpm /esat/micas-data/software/xilinx_vivado_2018.2/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-32140-pc-klas6-7.esat.kuleuven.be/realtime/drone_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top drone_wrapper
    rt::set_parameter enableIncremental true
    set rt::flattenHierarchy 3
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter inferFsm false
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops false
    rt::set_parameter synRetiming true
# MODE: 
    rt::set_parameter webTalkPath {/users/students/r0713047/Eagle/Eagle7/drone/drone.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-32140-pc-klas6-7.esat.kuleuven.be/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
