# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Thiba/OneDrive/Desktop/Eagle7/constraints/ZYBO_Master_2018.xdc

# Block Designs: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/drone.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone || ORIG_REF_NAME==drone} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_processing_system7_0_0/drone_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_processing_system7_0_0 || ORIG_REF_NAME==drone_processing_system7_0_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_RC_1_0/drone_RC_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_RC_1_0 || ORIG_REF_NAME==drone_RC_1_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_RC_0_0/drone_RC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_RC_0_0 || ORIG_REF_NAME==drone_RC_0_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_axi_gpio_testpins_0 || ORIG_REF_NAME==drone_axi_gpio_testpins_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_axi_gpio_led_0 || ORIG_REF_NAME==drone_axi_gpio_led_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_kill_switch_0_0/drone_kill_switch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_kill_switch_0_0 || ORIG_REF_NAME==drone_kill_switch_0_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_PWM_AXI_triple_0_0/drone_PWM_AXI_triple_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_PWM_AXI_triple_0_0 || ORIG_REF_NAME==drone_PWM_AXI_triple_0_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_PWM_AXI_triple_3_0/drone_PWM_AXI_triple_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_PWM_AXI_triple_3_0 || ORIG_REF_NAME==drone_PWM_AXI_triple_3_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_PWM_AXI_triple_5_0/drone_PWM_AXI_triple_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_PWM_AXI_triple_5_0 || ORIG_REF_NAME==drone_PWM_AXI_triple_5_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_100M_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_processing_system7_0_axi_periph_0/drone_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==drone_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_crypto2020_hash_ip_v1_0_0/drone_crypto2020_hash_ip_v1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_crypto2020_hash_ip_v1_0_0 || ORIG_REF_NAME==drone_crypto2020_hash_ip_v1_0_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_xadc_wiz_0_0/drone_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_xadc_wiz_0_0 || ORIG_REF_NAME==drone_xadc_wiz_0_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_PWM_AXI_triple_4_0/drone_PWM_AXI_triple_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_PWM_AXI_triple_4_0 || ORIG_REF_NAME==drone_PWM_AXI_triple_4_0} -quiet] -quiet

# IP: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_SWIPT_2020_0_0/drone_SWIPT_2020_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_SWIPT_2020_0_0 || ORIG_REF_NAME==drone_SWIPT_2020_0_0} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_xbar_0/drone_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_xbar_0 || ORIG_REF_NAME==drone_xbar_0} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_9/drone_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_9 || ORIG_REF_NAME==drone_auto_pc_9} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_0/drone_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_0 || ORIG_REF_NAME==drone_auto_pc_0} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_1/drone_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_1 || ORIG_REF_NAME==drone_auto_pc_1} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_2/drone_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_2 || ORIG_REF_NAME==drone_auto_pc_2} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_3/drone_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_3 || ORIG_REF_NAME==drone_auto_pc_3} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_4/drone_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_4 || ORIG_REF_NAME==drone_auto_pc_4} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_5/drone_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_5 || ORIG_REF_NAME==drone_auto_pc_5} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_6/drone_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_6 || ORIG_REF_NAME==drone_auto_pc_6} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_7/drone_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_7 || ORIG_REF_NAME==drone_auto_pc_7} -quiet] -quiet

# IP: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_8/drone_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==drone_auto_pc_8 || ORIG_REF_NAME==drone_auto_pc_8} -quiet] -quiet

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_processing_system7_0_0/drone_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_processing_system7_0_0 || ORIG_REF_NAME==drone_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_testpins_0 || ORIG_REF_NAME==drone_axi_gpio_testpins_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_axi_gpio_testpins_0/drone_axi_gpio_testpins_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_testpins_0 || ORIG_REF_NAME==drone_axi_gpio_testpins_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_led_0 || ORIG_REF_NAME==drone_axi_gpio_led_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_axi_gpio_led_0/drone_axi_gpio_led_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_axi_gpio_led_0 || ORIG_REF_NAME==drone_axi_gpio_led_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==drone_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_rst_processing_system7_0_100M_0/drone_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_xadc_wiz_0_0/drone_xadc_wiz_0_0_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_xadc_wiz_0_0/drone_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==drone_xadc_wiz_0_0 || ORIG_REF_NAME==drone_xadc_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_xbar_0/drone_xbar_0_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_9/drone_auto_pc_9_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_0/drone_auto_pc_0_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_1/drone_auto_pc_1_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_2/drone_auto_pc_2_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_3/drone_auto_pc_3_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_4/drone_auto_pc_4_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_5/drone_auto_pc_5_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_6/drone_auto_pc_6_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_7/drone_auto_pc_7_ooc.xdc

# XDC: c:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/ip/drone_auto_pc_8/drone_auto_pc_8_ooc.xdc

# XDC: C:/Users/Thiba/OneDrive/Desktop/Eagle7/src/bd/drone_ooc.xdc
